import { Pool, neonConfig } from '@neondatabase/serverless'
import { PrismaNeon } from '@prisma/adapter-neon'
import { PrismaClient } from '@prisma/client'
import ws from 'ws'
import { STARTER_CITIES } from './cities-data'

neonConfig.webSocketConstructor = ws
const pool = new Pool({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter: new PrismaNeon(pool) })

const treks = [
  // ─── Pakistan ───────────────────────────────────────────────────────────────
  {
    slug: 'fairy-meadows-pk',
    name: 'Fairy Meadows',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.3904,
    lon: 74.5765,
    trailheadElevation: 3300,
    summitElevation: 3969,
    difficulty: 'moderate',
    durationDays: 2,
    description: 'A breathtaking alpine meadow at the base of Nanga Parbat, offering some of the world\'s most dramatic mountain views.',
    popular: true,
  },
  {
    slug: 'k2-base-camp-pk',
    name: 'K2 Base Camp',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.8823,
    lon: 76.5133,
    trailheadElevation: 3050,
    summitElevation: 5150,
    difficulty: 'technical',
    durationDays: 14,
    description: 'The legendary trek through the Karakoram to the base of K2, the world\'s second-highest and deadliest mountain.',
    popular: true,
  },
  {
    slug: 'nanga-parbat-base-camp-pk',
    name: 'Nanga Parbat Base Camp (Rupal Face)',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.2356,
    lon: 74.5897,
    trailheadElevation: 2450,
    summitElevation: 4200,
    difficulty: 'hard',
    durationDays: 7,
    description: 'A challenging approach to the south face of Nanga Parbat, the Killer Mountain, through remote Rupal Valley.',
    popular: true,
  },
  {
    slug: 'rakaposhi-base-camp-pk',
    name: 'Rakaposhi Base Camp',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.1416,
    lon: 74.4929,
    trailheadElevation: 1950,
    summitElevation: 3800,
    difficulty: 'hard',
    durationDays: 5,
    description: 'A spectacular trek to the base of Rakaposhi (7788 m), offering one of the world\'s greatest vertical rises from road to summit.',
    popular: true,
  },
  {
    slug: 'rush-lake-pk',
    name: 'Rush Lake Trek',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.1895,
    lon: 74.7123,
    trailheadElevation: 2400,
    summitElevation: 4694,
    difficulty: 'hard',
    durationDays: 4,
    description: 'A challenging high-altitude trek to Rush Lake (4694 m), the highest lake in Pakistan, with sweeping views of Rakaposhi and Haramosh.',
    popular: true,
  },
  {
    slug: 'concordia-pk',
    name: 'Concordia (K2 Base Camp via Baltoro)',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.7443,
    lon: 76.4972,
    trailheadElevation: 3050,
    summitElevation: 4600,
    difficulty: 'technical',
    durationDays: 16,
    description: 'The Baltoro Glacier trek to Concordia, the meeting point of four massive glaciers surrounded by four 8000 m peaks.',
    popular: true,
  },
  {
    slug: 'naltar-valley-pk',
    name: 'Naltar Valley Lakes',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.2367,
    lon: 74.1734,
    trailheadElevation: 2898,
    summitElevation: 3600,
    difficulty: 'moderate',
    durationDays: 2,
    description: 'A rewarding trek through pine forests to multi-coloured alpine lakes in the scenic Naltar Valley.',
    popular: false,
  },
  {
    slug: 'deosai-plains-pk',
    name: 'Deosai National Park Trek',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.0236,
    lon: 75.5425,
    trailheadElevation: 3500,
    summitElevation: 4115,
    difficulty: 'moderate',
    durationDays: 3,
    description: 'Trekking the world\'s second-highest plateau, home to Himalayan brown bears, with panoramic views of Nanga Parbat.',
    popular: false,
  },
  {
    slug: 'haramosh-base-camp-pk',
    name: 'Haramosh Base Camp',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.1823,
    lon: 74.9012,
    trailheadElevation: 1500,
    summitElevation: 3600,
    difficulty: 'hard',
    durationDays: 5,
    description: 'A remote trek to the base of Haramosh Peak (7409 m), passing through beautiful villages and alpine terrain.',
    popular: false,
  },
  {
    slug: 'gondogoro-la-pk',
    name: 'Gondogoro La Pass',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 35.6989,
    lon: 76.5503,
    trailheadElevation: 3050,
    summitElevation: 5585,
    difficulty: 'technical',
    durationDays: 18,
    description: 'A high-altitude pass crossing (5585 m) on the K2 circuit, requiring crampons and ice axe, rewarding with views of four 8000 m peaks.',
    popular: false,
  },

  // ─── Nepal ──────────────────────────────────────────────────────────────────
  {
    slug: 'everest-base-camp-np',
    name: 'Everest Base Camp',
    country: 'Nepal',
    region: 'Khumbu',
    lat: 27.9881,
    lon: 86.9250,
    trailheadElevation: 2860,
    summitElevation: 5364,
    difficulty: 'hard',
    durationDays: 14,
    description: 'The world\'s most iconic trek, following the Sherpa trail through Sagarmatha National Park to the foot of Mt. Everest.',
    popular: true,
  },
  {
    slug: 'annapurna-circuit-np',
    name: 'Annapurna Circuit',
    country: 'Nepal',
    region: 'Annapurna',
    lat: 28.5964,
    lon: 83.9602,
    trailheadElevation: 820,
    summitElevation: 5416,
    difficulty: 'hard',
    durationDays: 18,
    description: 'A classic Himalayan circuit crossing the Thorong La Pass (5416 m) through diverse landscapes from subtropical to alpine.',
    popular: true,
  },
  {
    slug: 'annapurna-base-camp-np',
    name: 'Annapurna Base Camp',
    country: 'Nepal',
    region: 'Annapurna',
    lat: 28.5313,
    lon: 83.8775,
    trailheadElevation: 1070,
    summitElevation: 4130,
    difficulty: 'moderate',
    durationDays: 10,
    description: 'A stunning trek into the heart of the Annapurna Sanctuary, a glacial basin surrounded by ten peaks over 7000 m.',
    popular: true,
  },
  {
    slug: 'langtang-valley-np',
    name: 'Langtang Valley',
    country: 'Nepal',
    region: 'Langtang',
    lat: 28.2139,
    lon: 85.5569,
    trailheadElevation: 1430,
    summitElevation: 3870,
    difficulty: 'moderate',
    durationDays: 8,
    description: 'A beautiful valley trek close to Kathmandu through rhododendron forests to the Langtang glaciers.',
    popular: true,
  },
  {
    slug: 'manaslu-circuit-np',
    name: 'Manaslu Circuit',
    country: 'Nepal',
    region: 'Gorkha',
    lat: 28.5496,
    lon: 84.5597,
    trailheadElevation: 730,
    summitElevation: 5135,
    difficulty: 'hard',
    durationDays: 16,
    description: 'A remote circuit around the world\'s eighth-highest mountain, crossing the Larkya La Pass with stunning Himalayan views.',
    popular: true,
  },
  {
    slug: 'gokyo-lakes-np',
    name: 'Gokyo Lakes',
    country: 'Nepal',
    region: 'Khumbu',
    lat: 27.9597,
    lon: 86.6831,
    trailheadElevation: 2860,
    summitElevation: 4790,
    difficulty: 'hard',
    durationDays: 12,
    description: 'An alternative Everest region trek to the emerald Gokyo Lakes and Gokyo Ri for panoramic views of four 8000 m peaks.',
    popular: true,
  },
  {
    slug: 'upper-mustang-np',
    name: 'Upper Mustang',
    country: 'Nepal',
    region: 'Mustang',
    lat: 29.1805,
    lon: 83.9641,
    trailheadElevation: 2810,
    summitElevation: 4200,
    difficulty: 'moderate',
    durationDays: 12,
    description: 'A restricted-area trek through the ancient kingdom of Lo, a high-altitude Tibetan plateau with unique culture and red-rock canyons.',
    popular: false,
  },
  {
    slug: 'three-passes-np',
    name: 'Three Passes Trek (Khumbu)',
    country: 'Nepal',
    region: 'Khumbu',
    lat: 27.9881,
    lon: 86.9250,
    trailheadElevation: 2860,
    summitElevation: 5545,
    difficulty: 'technical',
    durationDays: 20,
    description: 'The ultimate Khumbu challenge crossing Kongma La (5535 m), Cho La (5420 m), and Renjo La (5360 m) with EBC as the centrepiece.',
    popular: false,
  },

  // ─── India ──────────────────────────────────────────────────────────────────
  {
    slug: 'valley-of-flowers-in',
    name: 'Valley of Flowers',
    country: 'India',
    region: 'Uttarakhand',
    lat: 30.7228,
    lon: 79.6077,
    trailheadElevation: 2650,
    summitElevation: 3658,
    difficulty: 'moderate',
    durationDays: 5,
    description: 'A UNESCO World Heritage trek through a vibrant alpine valley blooming with hundreds of Himalayan wildflowers.',
    popular: true,
  },
  {
    slug: 'roopkund-in',
    name: 'Roopkund Lake Trek',
    country: 'India',
    region: 'Uttarakhand',
    lat: 30.2499,
    lon: 79.7282,
    trailheadElevation: 2286,
    summitElevation: 5029,
    difficulty: 'hard',
    durationDays: 8,
    description: 'A high-altitude trek to the mysterious "Skeleton Lake" at 5029 m, surrounded by glaciers and high Himalayan peaks.',
    popular: true,
  },
  {
    slug: 'hampta-pass-in',
    name: 'Hampta Pass',
    country: 'India',
    region: 'Himachal Pradesh',
    lat: 32.2697,
    lon: 77.3026,
    trailheadElevation: 2050,
    summitElevation: 4270,
    difficulty: 'moderate',
    durationDays: 5,
    description: 'A dramatic crossover from the lush Kullu Valley to the barren Spiti Valley over the Hampta Pass (4270 m).',
    popular: true,
  },
  {
    slug: 'kedarkantha-in',
    name: 'Kedarkantha Peak',
    country: 'India',
    region: 'Uttarakhand',
    lat: 31.0178,
    lon: 78.1814,
    trailheadElevation: 2250,
    summitElevation: 3810,
    difficulty: 'moderate',
    durationDays: 6,
    description: 'One of India\'s best winter treks, climbing through snow-covered pine forests to Kedarkantha summit for 360° Himalayan views.',
    popular: true,
  },
  {
    slug: 'markha-valley-in',
    name: 'Markha Valley Trek',
    country: 'India',
    region: 'Ladakh',
    lat: 33.7782,
    lon: 77.6956,
    trailheadElevation: 3300,
    summitElevation: 5010,
    difficulty: 'hard',
    durationDays: 9,
    description: 'A classic Ladakhi trek crossing high mountain passes, visiting ancient monasteries, and traversing remote high-altitude valleys.',
    popular: true,
  },
  {
    slug: 'har-ki-dun-in',
    name: 'Har Ki Dun Valley',
    country: 'India',
    region: 'Uttarakhand',
    lat: 31.1605,
    lon: 78.4107,
    trailheadElevation: 1900,
    summitElevation: 3566,
    difficulty: 'easy',
    durationDays: 7,
    description: 'A picturesque cradle-shaped valley surrounded by peaks, home to ancient Himalayan villages with unique architecture.',
    popular: false,
  },

  // ─── Europe ─────────────────────────────────────────────────────────────────
  {
    slug: 'tour-du-mont-blanc-eu',
    name: 'Tour du Mont Blanc',
    country: 'France/Italy/Switzerland',
    region: 'Alps',
    lat: 45.8326,
    lon: 6.8652,
    trailheadElevation: 1035,
    summitElevation: 2537,
    difficulty: 'hard',
    durationDays: 11,
    description: 'Europe\'s most famous long-distance trail, circumnavigating Mont Blanc through three countries over 170 km.',
    popular: true,
  },
  {
    slug: 'mont-blanc-summit-eu',
    name: 'Mont Blanc Summit',
    country: 'France',
    region: 'Alps',
    lat: 45.8326,
    lon: 6.8652,
    trailheadElevation: 1035,
    summitElevation: 4808,
    difficulty: 'technical',
    durationDays: 3,
    description: 'Europe\'s highest peak (4808 m), typically climbed via the Gouter Route from Les Houches, requiring mountaineering skills.',
    popular: true,
  },
  {
    slug: 'matterhorn-eu',
    name: 'Matterhorn Hörnligrat',
    country: 'Switzerland',
    region: 'Valais Alps',
    lat: 45.9763,
    lon: 7.6586,
    trailheadElevation: 1620,
    summitElevation: 4478,
    difficulty: 'technical',
    durationDays: 2,
    description: 'One of the Alps\' most iconic climbs, ascending the classic Hörnligrat (Hornli Ridge) of the Matterhorn (4478 m).',
    popular: true,
  },
  {
    slug: 'walker-haute-route-eu',
    name: "Walker's Haute Route",
    country: 'France/Switzerland',
    region: 'Alps',
    lat: 45.9226,
    lon: 7.0534,
    trailheadElevation: 1035,
    summitElevation: 2894,
    difficulty: 'hard',
    durationDays: 14,
    description: 'A spectacular high-level route from Chamonix to Zermatt through remote alpine valleys and cols.',
    popular: false,
  },
  {
    slug: 'dolomites-alta-via-1-eu',
    name: 'Dolomites Alta Via 1',
    country: 'Italy',
    region: 'Dolomites',
    lat: 46.6167,
    lon: 12.2917,
    trailheadElevation: 1400,
    summitElevation: 2999,
    difficulty: 'moderate',
    durationDays: 9,
    description: 'A stunning hut-to-hut traverse of the UNESCO-listed Dolomites, from Lago di Braies to Belluno.',
    popular: true,
  },
  {
    slug: 'overland-track-tasmania-au',
    name: 'Overland Track',
    country: 'Australia',
    region: 'Tasmania',
    lat: -41.6500,
    lon: 145.9800,
    trailheadElevation: 1050,
    summitElevation: 1617,
    difficulty: 'moderate',
    durationDays: 6,
    description: 'Australia\'s most famous multi-day alpine trek through Cradle Mountain-Lake St Clair National Park.',
    popular: true,
  },
  {
    slug: 'gr20-corsica-eu',
    name: 'GR20 Corsica',
    country: 'France',
    region: 'Corsica',
    lat: 42.0964,
    lon: 9.1286,
    trailheadElevation: 1100,
    summitElevation: 2706,
    difficulty: 'technical',
    durationDays: 16,
    description: 'Europe\'s toughest long-distance trail, crossing Corsica\'s wild interior from Calenzana to Conca.',
    popular: true,
  },

  // ─── UK ─────────────────────────────────────────────────────────────────────
  {
    slug: 'snowdon-uk',
    name: 'Snowdon (Yr Wyddfa)',
    country: 'United Kingdom',
    region: 'Wales',
    lat: 53.0686,
    lon: -4.0762,
    trailheadElevation: 105,
    summitElevation: 1085,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'Wales\' highest peak and the highest mountain in the UK outside Scotland, with multiple well-marked routes to the summit.',
    popular: true,
  },
  {
    slug: 'ben-nevis-uk',
    name: 'Ben Nevis',
    country: 'United Kingdom',
    region: 'Scotland',
    lat: 56.7969,
    lon: -5.0036,
    trailheadElevation: 15,
    summitElevation: 1345,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'The highest mountain in the British Isles, climbed via the Mountain Track (tourist path) or the more technical Carn Mor Dearg Arete.',
    popular: true,
  },
  {
    slug: 'scafell-pike-uk',
    name: 'Scafell Pike',
    country: 'United Kingdom',
    region: 'England',
    lat: 54.4541,
    lon: -3.2116,
    trailheadElevation: 90,
    summitElevation: 978,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'England\'s highest peak in the heart of the Lake District, accessed via several routes from Wasdale Head or Borrowdale.',
    popular: true,
  },
  {
    slug: 'west-highland-way-uk',
    name: 'West Highland Way',
    country: 'United Kingdom',
    region: 'Scotland',
    lat: 55.9413,
    lon: -4.5588,
    trailheadElevation: 5,
    summitElevation: 548,
    difficulty: 'moderate',
    durationDays: 8,
    description: 'Scotland\'s most famous long-distance footpath from Milngavie to Fort William, through Loch Lomond and the Highlands.',
    popular: true,
  },
  {
    slug: 'pembrokeshire-coast-path-uk',
    name: 'Pembrokeshire Coast Path',
    country: 'United Kingdom',
    region: 'Wales',
    lat: 51.8650,
    lon: -5.1760,
    trailheadElevation: 0,
    summitElevation: 175,
    difficulty: 'moderate',
    durationDays: 14,
    description: 'A spectacular 186-mile National Trail along the Pembrokeshire coastline, with dramatic cliffs, beaches, and seabird colonies.',
    popular: false,
  },

  // ─── USA ────────────────────────────────────────────────────────────────────
  {
    slug: 'john-muir-trail-us',
    name: 'John Muir Trail',
    country: 'United States',
    region: 'California',
    lat: 37.7389,
    lon: -119.5592,
    trailheadElevation: 1199,
    summitElevation: 4421,
    difficulty: 'hard',
    durationDays: 21,
    description: 'A legendary 211-mile trail through the Sierra Nevada from Yosemite Valley to Mt. Whitney, the highest peak in the contiguous US.',
    popular: true,
  },
  {
    slug: 'appalachian-trail-us',
    name: 'Appalachian Trail (Thru-Hike)',
    country: 'United States',
    region: 'Eastern US',
    lat: 34.6278,
    lon: -84.1943,
    trailheadElevation: 547,
    summitElevation: 2025,
    difficulty: 'hard',
    durationDays: 165,
    description: 'The iconic 2190-mile trail from Springer Mountain, Georgia, to Mount Katahdin, Maine, attracting thousands of thru-hikers each year.',
    popular: true,
  },
  {
    slug: 'grand-canyon-rim-to-rim-us',
    name: 'Grand Canyon Rim to Rim',
    country: 'United States',
    region: 'Arizona',
    lat: 36.0544,
    lon: -112.1401,
    trailheadElevation: 2440,
    summitElevation: 2440,
    difficulty: 'hard',
    durationDays: 3,
    description: 'A challenging cross-canyon hike from the North Rim to the South Rim (or vice versa) through one of Earth\'s greatest geological wonders.',
    popular: true,
  },
  {
    slug: 'half-dome-us',
    name: 'Half Dome',
    country: 'United States',
    region: 'California',
    lat: 37.7459,
    lon: -119.5332,
    trailheadElevation: 1199,
    summitElevation: 2694,
    difficulty: 'hard',
    durationDays: 1,
    description: 'One of Yosemite\'s most iconic hikes, culminating in a cable-assisted climb to the famous granite dome summit.',
    popular: true,
  },
  {
    slug: 'rainier-summit-us',
    name: 'Mt. Rainier Summit (Disappointment Cleaver)',
    country: 'United States',
    region: 'Washington',
    lat: 46.8523,
    lon: -121.7603,
    trailheadElevation: 1646,
    summitElevation: 4392,
    difficulty: 'technical',
    durationDays: 3,
    description: 'A glacier-clad volcanic summit requiring crampons, ice axe, and rope skills, the most-climbed glaciated peak in North America.',
    popular: true,
  },
  {
    slug: 'pacific-crest-trail-us',
    name: 'Pacific Crest Trail (Thru-Hike)',
    country: 'United States',
    region: 'Western US',
    lat: 32.5894,
    lon: -116.4683,
    trailheadElevation: 800,
    summitElevation: 4009,
    difficulty: 'hard',
    durationDays: 150,
    description: 'A 2650-mile trail from the Mexican border to Manning Park, Canada, through the Mojave Desert, Sierra Nevada, and Cascades.',
    popular: true,
  },
  {
    slug: 'glacier-national-park-highline-us',
    name: 'Highline Trail (Glacier NP)',
    country: 'United States',
    region: 'Montana',
    lat: 48.6959,
    lon: -113.7178,
    trailheadElevation: 2026,
    summitElevation: 2182,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'A dramatic cliff-edge trail in Glacier National Park with sweeping views of the Continental Divide and hanging valleys.',
    popular: true,
  },
  {
    slug: 'zion-narrows-us',
    name: 'Zion Narrows',
    country: 'United States',
    region: 'Utah',
    lat: 37.2982,
    lon: -112.9479,
    trailheadElevation: 1180,
    summitElevation: 1180,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'A unique slot-canyon hike through the Virgin River gorge with walls up to 300 m high and only 6 m wide in places.',
    popular: true,
  },
  {
    slug: 'angels-landing-us',
    name: "Angel's Landing",
    country: 'United States',
    region: 'Utah',
    lat: 37.2684,
    lon: -112.9492,
    trailheadElevation: 1180,
    summitElevation: 1763,
    difficulty: 'hard',
    durationDays: 1,
    description: 'A thrilling chain-assisted scramble to a narrow sandstone fin above Zion Canyon, requiring a permit and confidence with exposure.',
    popular: true,
  },

  // ─── South America ───────────────────────────────────────────────────────────
  {
    slug: 'inca-trail-pe',
    name: 'Inca Trail to Machu Picchu',
    country: 'Peru',
    region: 'Cusco',
    lat: -13.1631,
    lon: -72.5456,
    trailheadElevation: 2720,
    summitElevation: 4215,
    difficulty: 'hard',
    durationDays: 4,
    description: 'The world\'s most celebrated archaeological trek, following the ancient Inca road network to the iconic Machu Picchu citadel.',
    popular: true,
  },
  {
    slug: 'torres-del-paine-o-circuit-cl',
    name: 'Torres del Paine O Circuit',
    country: 'Chile',
    region: 'Patagonia',
    lat: -51.1335,
    lon: -72.9753,
    trailheadElevation: 50,
    summitElevation: 1241,
    difficulty: 'hard',
    durationDays: 9,
    description: 'The full circuit around the iconic Torres del Paine massif in Chilean Patagonia, combining the W Trek with the remote back circuit.',
    popular: true,
  },
  {
    slug: 'torres-del-paine-w-cl',
    name: 'Torres del Paine W Trek',
    country: 'Chile',
    region: 'Patagonia',
    lat: -51.1335,
    lon: -72.9753,
    trailheadElevation: 50,
    summitElevation: 1241,
    difficulty: 'moderate',
    durationDays: 5,
    description: 'The classic W-shaped route through Torres del Paine, visiting the iconic granite towers, French Valley, and Grey Glacier.',
    popular: true,
  },
  {
    slug: 'aconcagua-normal-ar',
    name: 'Aconcagua Normal Route',
    country: 'Argentina',
    region: 'Mendoza',
    lat: -32.6532,
    lon: -70.0109,
    trailheadElevation: 2950,
    summitElevation: 6961,
    difficulty: 'technical',
    durationDays: 20,
    description: 'The ascent of Aconcagua (6961 m), the highest peak in the Western and Southern hemispheres, via the non-technical Normal Route.',
    popular: true,
  },
  {
    slug: 'huayhuash-circuit-pe',
    name: 'Cordillera Huayhuash Circuit',
    country: 'Peru',
    region: 'Ancash',
    lat: -10.2594,
    lon: -76.9103,
    trailheadElevation: 3300,
    summitElevation: 5000,
    difficulty: 'hard',
    durationDays: 12,
    description: 'A remote Andean circuit through the world\'s second-highest tropical mountain range, with stunning glacier lakes and 6000 m peaks.',
    popular: false,
  },
  {
    slug: 'fitz-roy-ar',
    name: 'Fitz Roy Trek (Laguna de los Tres)',
    country: 'Argentina',
    region: 'Patagonia',
    lat: -49.2717,
    lon: -73.0444,
    trailheadElevation: 230,
    summitElevation: 1200,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'The iconic day hike to Laguna de los Tres for a dramatic up-close view of the jagged granite towers of Fitz Roy.',
    popular: true,
  },
  {
    slug: 'lares-trek-pe',
    name: 'Lares Trek',
    country: 'Peru',
    region: 'Cusco',
    lat: -13.2050,
    lon: -72.0814,
    trailheadElevation: 3850,
    summitElevation: 4450,
    difficulty: 'moderate',
    durationDays: 4,
    description: 'An off-the-beaten-path alternative to the Inca Trail, passing through authentic Quechua weaving communities and hot springs.',
    popular: false,
  },

  // ─── Africa ─────────────────────────────────────────────────────────────────
  {
    slug: 'kilimanjaro-marangu-tz',
    name: 'Kilimanjaro - Marangu Route',
    country: 'Tanzania',
    region: 'Kilimanjaro',
    lat: -3.0674,
    lon: 37.3556,
    trailheadElevation: 1879,
    summitElevation: 5895,
    difficulty: 'hard',
    durationDays: 6,
    description: 'The "Coca-Cola Route" to Africa\'s highest peak (5895 m), the least strenuous Kilimanjaro route with hut accommodation.',
    popular: true,
  },
  {
    slug: 'kilimanjaro-machame-tz',
    name: 'Kilimanjaro - Machame Route',
    country: 'Tanzania',
    region: 'Kilimanjaro',
    lat: -3.0674,
    lon: 37.3556,
    trailheadElevation: 1800,
    summitElevation: 5895,
    difficulty: 'hard',
    durationDays: 7,
    description: 'The "Whiskey Route" — a scenic, challenging approach to Uhuru Peak with better acclimatization profile and high success rate.',
    popular: true,
  },
  {
    slug: 'atlas-toubkal-ma',
    name: 'Mt. Toubkal Summit',
    country: 'Morocco',
    region: 'High Atlas',
    lat: 31.0597,
    lon: -7.9156,
    trailheadElevation: 1740,
    summitElevation: 4167,
    difficulty: 'hard',
    durationDays: 2,
    description: 'North Africa\'s highest peak (4167 m), climbed from Imlil village through the Atlas Mountains\' stunning landscapes.',
    popular: true,
  },
  {
    slug: 'rwenzori-mountains-ug',
    name: 'Rwenzori Mountains - Margherita Peak',
    country: 'Uganda',
    region: 'Rwenzori',
    lat: 0.3833,
    lon: 29.8667,
    trailheadElevation: 1590,
    summitElevation: 5109,
    difficulty: 'technical',
    durationDays: 8,
    description: 'A unique glaciated equatorial trek to Africa\'s third-highest peak through bizarre Afroalpine vegetation zones.',
    popular: false,
  },
  {
    slug: 'simien-mountains-et',
    name: 'Simien Mountains Trek',
    country: 'Ethiopia',
    region: 'Amhara',
    lat: 13.2167,
    lon: 38.0667,
    trailheadElevation: 2800,
    summitElevation: 4550,
    difficulty: 'moderate',
    durationDays: 7,
    description: 'A UNESCO World Heritage site trek through dramatic escarpments, home to gelada baboons, Ethiopian wolves, and endemic birds.',
    popular: false,
  },

  // ─── New Zealand ─────────────────────────────────────────────────────────────
  {
    slug: 'milford-track-nz',
    name: 'Milford Track',
    country: 'New Zealand',
    region: 'Fiordland',
    lat: -44.6714,
    lon: 168.0369,
    trailheadElevation: 210,
    summitElevation: 1154,
    difficulty: 'moderate',
    durationDays: 4,
    description: '"The Finest Walk in the World" through Fiordland National Park, ending at the iconic Milford Sound.',
    popular: true,
  },
  {
    slug: 'routeburn-track-nz',
    name: 'Routeburn Track',
    country: 'New Zealand',
    region: 'Mount Aspiring / Fiordland',
    lat: -44.7271,
    lon: 168.1408,
    trailheadElevation: 520,
    summitElevation: 1255,
    difficulty: 'moderate',
    durationDays: 3,
    description: 'A premier Great Walk through two national parks, crossing the alpine Harris Saddle with panoramic views of the Harris Mountains.',
    popular: true,
  },
  {
    slug: 'tongariro-alpine-crossing-nz',
    name: 'Tongariro Alpine Crossing',
    country: 'New Zealand',
    region: 'Tongariro',
    lat: -39.1552,
    lon: 175.6421,
    trailheadElevation: 1119,
    summitElevation: 1886,
    difficulty: 'hard',
    durationDays: 1,
    description: 'New Zealand\'s best one-day hike, crossing the active volcanic Tongariro massif past emerald lakes, craters, and lava flows.',
    popular: true,
  },

  // ─── Japan ───────────────────────────────────────────────────────────────────
  {
    slug: 'mt-fuji-yoshida-jp',
    name: 'Mt. Fuji - Yoshida Trail',
    country: 'Japan',
    region: 'Yamanashi/Shizuoka',
    lat: 35.3606,
    lon: 138.7274,
    trailheadElevation: 2305,
    summitElevation: 3776,
    difficulty: 'hard',
    durationDays: 2,
    description: 'The classic ascent of Japan\'s sacred volcano, the most climbed 3000+ m peak in the world, via the traditional Yoshida Trail.',
    popular: true,
  },
  {
    slug: 'nakasendo-way-jp',
    name: 'Nakasendo Way (Magome to Tsumago)',
    country: 'Japan',
    region: 'Nagano/Gifu',
    lat: 35.5286,
    lon: 137.5538,
    trailheadElevation: 600,
    summitElevation: 801,
    difficulty: 'easy',
    durationDays: 1,
    description: 'The most scenic section of the ancient Nakasendo post road, connecting two beautifully preserved Edo-period post towns.',
    popular: true,
  },

  // ─── Central Asia ─────────────────────────────────────────────────────────────
  {
    slug: 'fan-mountains-tj',
    name: 'Fan Mountains Trek',
    country: 'Tajikistan',
    region: 'Sughd',
    lat: 39.3333,
    lon: 68.5167,
    trailheadElevation: 2200,
    summitElevation: 4208,
    difficulty: 'hard',
    durationDays: 10,
    description: 'A remote traverse through the Fan Mountains, home to seven stunning turquoise lakes and peaks up to 5000 m.',
    popular: false,
  },
  {
    slug: 'alta-kel-kg',
    name: 'Ala Kul Lake Trek',
    country: 'Kyrgyzstan',
    region: 'Issyk-Kul',
    lat: 42.3689,
    lon: 78.4872,
    trailheadElevation: 1750,
    summitElevation: 3532,
    difficulty: 'hard',
    durationDays: 4,
    description: 'A spectacular mountain circuit near Karakol through the Terskey Alatau mountains to a stunning high-altitude turquoise lake.',
    popular: false,
  },
  {
    slug: 'song-kul-kg',
    name: 'Song Kul Horse Trek',
    country: 'Kyrgyzstan',
    region: 'Naryn',
    lat: 41.8333,
    lon: 75.1500,
    trailheadElevation: 2600,
    summitElevation: 3600,
    difficulty: 'moderate',
    durationDays: 5,
    description: 'A pastoral alpine journey by horseback across Kyrgyz steppes to Song Kul, the second-largest lake in Kyrgyzstan at 3016 m.',
    popular: false,
  },

  // ─── Middle East ──────────────────────────────────────────────────────────────
  {
    slug: 'dana-to-petra-jo',
    name: 'Dana to Petra Trek',
    country: 'Jordan',
    region: 'Ma\'an',
    lat: 30.6860,
    lon: 35.6220,
    trailheadElevation: 1500,
    summitElevation: 1700,
    difficulty: 'hard',
    durationDays: 4,
    description: 'A wild desert traverse through Wadi Araba and Wadi Rum landscapes, ending at the ancient Nabataean city of Petra.',
    popular: false,
  },
  {
    slug: 'wadi-rum-jo',
    name: 'Wadi Rum Desert Trek',
    country: 'Jordan',
    region: 'Aqaba',
    lat: 29.5806,
    lon: 35.4239,
    trailheadElevation: 900,
    summitElevation: 1754,
    difficulty: 'moderate',
    durationDays: 3,
    description: 'Trekking through the iconic red sandstone desert of Wadi Rum, the "Valley of the Moon", with Bedouin camps and ancient rock art.',
    popular: true,
  },

  // ─── Scandinavia ──────────────────────────────────────────────────────────────
  {
    slug: 'trolltunga-no',
    name: 'Trolltunga',
    country: 'Norway',
    region: 'Vestland',
    lat: 60.1242,
    lon: 6.7399,
    trailheadElevation: 866,
    summitElevation: 1180,
    difficulty: 'hard',
    durationDays: 1,
    description: 'One of Norway\'s most dramatic hikes to the iconic "Troll\'s Tongue" rock formation jutting 700 m above Lake Ringedalsvatnet.',
    popular: true,
  },
  {
    slug: 'preikestolen-no',
    name: 'Preikestolen (Pulpit Rock)',
    country: 'Norway',
    region: 'Rogaland',
    lat: 58.9864,
    lon: 6.1893,
    trailheadElevation: 270,
    summitElevation: 604,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'The famous flat-topped cliff rising 604 m above the Lysefjord, one of Norway\'s most visited natural attractions.',
    popular: true,
  },
  {
    slug: 'kungsleden-se',
    name: 'Kungsleden (King\'s Trail)',
    country: 'Sweden',
    region: 'Lapland',
    lat: 68.3583,
    lon: 18.6550,
    trailheadElevation: 450,
    summitElevation: 1420,
    difficulty: 'moderate',
    durationDays: 14,
    description: 'Sweden\'s most famous long-distance trail through Lapland from Abisko to Hemavan, crossing untouched arctic wilderness.',
    popular: false,
  },

  // ─── Greece & Turkey ──────────────────────────────────────────────────────────
  {
    slug: 'lycian-way-tr',
    name: 'Lycian Way',
    country: 'Turkey',
    region: 'Antalya/Mugla',
    lat: 36.5406,
    lon: 29.1186,
    trailheadElevation: 0,
    summitElevation: 1950,
    difficulty: 'hard',
    durationDays: 25,
    description: 'Turkey\'s first long-distance trail, following ancient Lycian paths along 500 km of dramatic Mediterranean coastline.',
    popular: false,
  },
  {
    slug: 'mount-olympus-gr',
    name: 'Mount Olympus - Mytikas',
    country: 'Greece',
    region: 'Thessaly/Macedonia',
    lat: 40.0856,
    lon: 22.3586,
    trailheadElevation: 1100,
    summitElevation: 2918,
    difficulty: 'hard',
    durationDays: 2,
    description: 'Climbing Greece\'s highest mountain and mythological home of the gods to the summit of Mytikas (2918 m).',
    popular: false,
  },

  // ─── China & Tibet ────────────────────────────────────────────────────────────
  {
    slug: 'tiger-leaping-gorge-cn',
    name: 'Tiger Leaping Gorge',
    country: 'China',
    region: 'Yunnan',
    lat: 27.2258,
    lon: 100.0772,
    trailheadElevation: 1800,
    summitElevation: 2670,
    difficulty: 'moderate',
    durationDays: 2,
    description: 'A spectacular two-day hike above one of the world\'s deepest gorges, cut by the Yangtze River between Jade Dragon Snow Mountain and Haba Snow Mountain.',
    popular: true,
  },
  {
    slug: 'kora-kailash-cn',
    name: 'Mt. Kailash Kora',
    country: 'China',
    region: 'Tibet',
    lat: 31.0677,
    lon: 81.3119,
    trailheadElevation: 4580,
    summitElevation: 5630,
    difficulty: 'hard',
    durationDays: 4,
    description: 'A sacred 52 km circumambulation of Mt. Kailash (6638 m), the holiest mountain in Asia, crossing the Dolma La Pass at 5630 m.',
    popular: false,
  },
  {
    slug: 'emei-shan-cn',
    name: 'Emei Shan (Mt. Emei)',
    country: 'China',
    region: 'Sichuan',
    lat: 29.5197,
    lon: 103.3328,
    trailheadElevation: 550,
    summitElevation: 3099,
    difficulty: 'moderate',
    durationDays: 2,
    description: 'One of the Four Sacred Buddhist Mountains of China, with ancient temples, golden summit shrine, and elusive sea of clouds.',
    popular: false,
  },

  // ─── Southeast Asia ───────────────────────────────────────────────────────────
  {
    slug: 'mt-kinabalu-my',
    name: 'Mt. Kinabalu Summit',
    country: 'Malaysia',
    region: 'Sabah',
    lat: 6.0750,
    lon: 116.5581,
    trailheadElevation: 1558,
    summitElevation: 4095,
    difficulty: 'hard',
    durationDays: 2,
    description: 'Southeast Asia\'s highest peak (4095 m) in Borneo, requiring a guided two-day ascent with an overnight stay at Laban Rata hut.',
    popular: true,
  },
  {
    slug: 'mt-rinjani-id',
    name: 'Mt. Rinjani Summit',
    country: 'Indonesia',
    region: 'Lombok',
    lat: -8.4167,
    lon: 116.4667,
    trailheadElevation: 600,
    summitElevation: 3726,
    difficulty: 'hard',
    durationDays: 3,
    description: 'Indonesia\'s second-highest volcano (3726 m) with a stunning crater lake, active inner cone, and demanding trail to the summit.',
    popular: true,
  },
  {
    slug: 'pinatubo-trekph',
    name: 'Mt. Pinatubo Crater Lake',
    country: 'Philippines',
    region: 'Luzon',
    lat: 15.1425,
    lon: 120.3497,
    trailheadElevation: 475,
    summitElevation: 1445,
    difficulty: 'moderate',
    durationDays: 1,
    description: 'A scenic trek through lahar-formed badlands to the stunning turquoise crater lake of the volcano that had the century\'s largest eruption in 1991.',
    popular: false,
  },

  // ─── North Africa ─────────────────────────────────────────────────────────────
  {
    slug: 'sahara-tassili-dz',
    name: 'Tassili n\'Ajjer Trek',
    country: 'Algeria',
    region: 'Tamanrasset',
    lat: 25.4833,
    lon: 8.4167,
    trailheadElevation: 1100,
    summitElevation: 2158,
    difficulty: 'hard',
    durationDays: 7,
    description: 'A remote Saharan plateau trek through surreal rock forests and ancient cave art sites in a UNESCO World Heritage landscape.',
    popular: false,
  },

  // ─── Additional Pakistan treks ─────────────────────────────────────────────
  {
    slug: 'batura-glacier-pk',
    name: 'Batura Glacier Trek',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.5086,
    lon: 74.5253,
    trailheadElevation: 2500,
    summitElevation: 4200,
    difficulty: 'hard',
    durationDays: 6,
    description: 'Trekking along one of the world\'s longest glaciers outside the polar regions, in the Hunza Valley with stunning views of the Batura Muztagh.',
    popular: false,
  },
  {
    slug: 'shimshal-pass-pk',
    name: 'Shimshal Pass Trek',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.9167,
    lon: 75.3333,
    trailheadElevation: 3050,
    summitElevation: 4735,
    difficulty: 'technical',
    durationDays: 10,
    description: 'A remote and spectacular trek to the high Shimshal Pass used by Wakhis for centuries to drive their yaks to summer pastures.',
    popular: false,
  },
  {
    slug: 'broghil-pass-pk',
    name: 'Broghil Pass Trek',
    country: 'Pakistan',
    region: 'Khyber Pakhtunkhwa',
    lat: 36.9167,
    lon: 73.2500,
    trailheadElevation: 2800,
    summitElevation: 3798,
    difficulty: 'hard',
    durationDays: 8,
    description: 'A remote high-altitude trek through the Broghil Valley and over the historic Broghil Pass on the Afghan border.',
    popular: false,
  },
  {
    slug: 'karambar-lake-pk',
    name: 'Karambar Lake Trek',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.9833,
    lon: 73.5667,
    trailheadElevation: 2300,
    summitElevation: 4272,
    difficulty: 'hard',
    durationDays: 6,
    description: 'Trek to Karambar Lake (4272 m), one of Pakistan\'s highest and most beautiful high-altitude lakes in the remote Ishkoman district.',
    popular: false,
  },
  {
    slug: 'passu-glacier-pk',
    name: 'Passu Glacier & Cathedrals',
    country: 'Pakistan',
    region: 'Gilgit-Baltistan',
    lat: 36.4750,
    lon: 74.8742,
    trailheadElevation: 2450,
    summitElevation: 3500,
    difficulty: 'moderate',
    durationDays: 2,
    description: 'A scenic trek near Passu village alongside a massive glacier and beneath the dramatic "Cathedral" rock towers above the Karakoram Highway.',
    popular: false,
  },

  // ─── Additional Nepal treks ───────────────────────────────────────────────
  {
    slug: 'kanchenjunga-base-camp-np',
    name: 'Kanchenjunga Base Camp',
    country: 'Nepal',
    region: 'Taplejung',
    lat: 27.7025,
    lon: 88.1473,
    trailheadElevation: 1090,
    summitElevation: 5143,
    difficulty: 'technical',
    durationDays: 20,
    description: 'A remote and demanding trek to the base of the world\'s third-highest mountain (8586 m) in far eastern Nepal.',
    popular: false,
  },
  {
    slug: 'dolpo-nepal-np',
    name: 'Dolpo Trek (Upper Dolpo)',
    country: 'Nepal',
    region: 'Karnali',
    lat: 29.0000,
    lon: 83.0000,
    trailheadElevation: 2100,
    summitElevation: 5360,
    difficulty: 'technical',
    durationDays: 25,
    description: 'One of Nepal\'s most remote restricted-area treks through the ancient Bon Buddhist culture of Dolpo, the inspiration for Peter Matthiessen\'s "The Snow Leopard".',
    popular: false,
  },

  // ─── More Africa ──────────────────────────────────────────────────────────────
  {
    slug: 'drakensberg-traverse-za',
    name: 'Drakensberg Grand Traverse',
    country: 'South Africa',
    region: 'KwaZulu-Natal',
    lat: -29.4680,
    lon: 29.2510,
    trailheadElevation: 1400,
    summitElevation: 3446,
    difficulty: 'hard',
    durationDays: 15,
    description: 'A challenging traverse along the roof of southern Africa through the Drakensberg escarpment and Lesotho highlands.',
    popular: false,
  },

  // ─── Canada ───────────────────────────────────────────────────────────────────
  {
    slug: 'west-coast-trail-ca',
    name: 'West Coast Trail',
    country: 'Canada',
    region: 'British Columbia',
    lat: 48.7833,
    lon: -124.7167,
    trailheadElevation: 0,
    summitElevation: 200,
    difficulty: 'hard',
    durationDays: 7,
    description: 'A legendary and demanding coastal wilderness trail on Vancouver Island, requiring ladders, cable cars, and tidal timing.',
    popular: true,
  },
  {
    slug: 'skyline-trail-canada-ca',
    name: 'Skyline Trail (Jasper)',
    country: 'Canada',
    region: 'Alberta',
    lat: 52.8849,
    lon: -118.0817,
    trailheadElevation: 1697,
    summitElevation: 2400,
    difficulty: 'moderate',
    durationDays: 3,
    description: 'A spectacular high-elevation traverse through Jasper National Park above the treeline with sweeping views of the Canadian Rockies.',
    popular: false,
  },

  // ─── Iceland ──────────────────────────────────────────────────────────────────
  {
    slug: 'laugavegur-is',
    name: 'Laugavegur Trail',
    country: 'Iceland',
    region: 'Highlands',
    lat: 63.9881,
    lon: -19.0581,
    trailheadElevation: 1100,
    summitElevation: 1100,
    difficulty: 'moderate',
    durationDays: 4,
    description: 'Iceland\'s most famous multi-day trail through vivid rhyolite mountains, geothermal hot springs, black sand deserts, and glaciers.',
    popular: true,
  },

  // ─── Georgia (Caucasus) ────────────────────────────────────────────────────────
  {
    slug: 'kazbegi-ge',
    name: 'Kazbegi - Gergeti Trinity Church & Kazbek',
    country: 'Georgia',
    region: 'Mtskheta-Mtianeti',
    lat: 42.6650,
    lon: 44.6286,
    trailheadElevation: 1750,
    summitElevation: 5047,
    difficulty: 'technical',
    durationDays: 3,
    description: 'Starting with the iconic Gergeti Trinity Church hike, progressing to the technical ascent of Mt. Kazbek (5047 m), a Caucasus giant.',
    popular: true,
  },
]

async function main() {
  console.log('Seeding trek database...')
  for (const trek of treks) {
    await prisma.trek.upsert({ where: { slug: trek.slug }, update: trek, create: trek })
  }
  console.log(`Seeded ${treks.length} treks.`)

  console.log('Seeding starter cities...')
  for (const city of STARTER_CITIES) {
    await prisma.city.upsert({ where: { id: city.id }, update: city, create: city })
  }
  console.log(`Seeded ${STARTER_CITIES.length} cities.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await pool.end()
  })
