import type { Metadata } from 'next'
import Link from 'next/link'
import { Header } from '@/components/ui/Header'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'PeakWeather terms of service — conditions for using the platform.',
  alternates: { canonical: '/terms' },
  robots: { index: false, follow: false },
}

const UPDATED = '18 September 2026'

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-extrabold text-gray-900 dark:text-gray-100 mb-1">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: {UPDATED}</p>

        <Section title="1. Acceptance">
          <p className="text-gray-700 dark:text-gray-300">
            By accessing PeakWeather (&ldquo;the Service&rdquo;), you agree to these Terms. If you
            disagree, please stop using the Service.
          </p>
        </Section>

        <Section title="2. Nature of the Service">
          <p className="text-gray-700 dark:text-gray-300">
            PeakWeather provides weather information and AI-generated trek safety verdicts for
            informational purposes only. We aggregate data from third-party meteorological services
            (MET Norway, OpenWeatherMap, RainViewer) and generate AI verdicts via Anthropic Claude.
          </p>
        </Section>

        <Section title="3. AI verdicts — important disclaimer">
          <p className="text-gray-700 dark:text-gray-300">
            Trek safety verdicts (GO / CAUTION / NO-GO) are generated by a large language model
            and are <strong>for guidance only</strong>. They do not constitute professional
            mountaineering, safety, or medical advice. Weather and mountain conditions change
            rapidly and unpredictably.
          </p>
          <p className="text-gray-700 dark:text-gray-300 mt-2">
            <strong>
              You are solely responsible for decisions relating to outdoor and mountain activities.
              Always check official forecasts, consult local guides, and exercise independent
              judgement. Never rely solely on AI-generated verdicts for safety-critical decisions.
            </strong>
          </p>
        </Section>

        <Section title="4. Weather accuracy">
          <p className="text-gray-700 dark:text-gray-300">
            Weather forecasts are provided &ldquo;as is&rdquo; from third-party numerical weather
            prediction models. Accuracy decreases at longer forecast horizons. PeakWeather makes
            no warranty regarding forecast accuracy.
          </p>
        </Section>

        <Section title="5. Third-party attributions">
          <ul className="list-disc pl-5 space-y-1 text-gray-700 dark:text-gray-300">
            <li>
              Weather data: MET Norway Locationforecast 2.0 — licensed under{' '}
              <a
                href="https://creativecommons.org/licenses/by/4.0/"
                target="_blank"
                rel="noopener noreferrer"
                className="underline text-blue-600 dark:text-blue-400"
              >
                CC BY 4.0
              </a>
              . Source:{' '}
              <a
                href="https://api.met.no/"
                target="_blank"
                rel="noopener noreferrer"
                className="underline text-blue-600 dark:text-blue-400"
              >
                api.met.no
              </a>
              .
            </li>
            <li>
              Radar: RainViewer — subject to{' '}
              <a
                href="https://www.rainviewer.com/api.html"
                target="_blank"
                rel="noopener noreferrer"
                className="underline text-blue-600 dark:text-blue-400"
              >
                RainViewer API terms
              </a>
              .
            </li>
            <li>Map tiles: OpenStreetMap contributors (ODbL).</li>
            <li>City data: GeoNames (CC BY 4.0).</li>
            <li>AI: Anthropic Claude — subject to Anthropic&apos;s usage policies.</li>
          </ul>
        </Section>

        <Section title="6. Acceptable use">
          <p className="text-gray-700 dark:text-gray-300">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 text-gray-700 dark:text-gray-300">
            <li>Scrape or systematically harvest data from the Service at scale</li>
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to circumvent rate limits or security measures</li>
            <li>Republish AI-generated verdicts as authoritative safety guidance</li>
          </ul>
        </Section>

        <Section title="7. Limitation of liability">
          <p className="text-gray-700 dark:text-gray-300">
            To the maximum extent permitted by law, PeakWeather and its operators shall not be
            liable for any injury, death, property damage, or financial loss arising from use of
            or reliance on the Service, including AI-generated verdicts or weather forecasts.
            The Service is provided &ldquo;as is&rdquo; without warranty of any kind.
          </p>
        </Section>

        <Section title="8. Intellectual property">
          <p className="text-gray-700 dark:text-gray-300">
            Original content and design on PeakWeather is owned by us. Third-party data and
            content remains the property of respective rights holders (see §5).
          </p>
        </Section>

        <Section title="9. Changes">
          <p className="text-gray-700 dark:text-gray-300">
            We may update these Terms. The &ldquo;Last updated&rdquo; date reflects the most recent
            revision. Continued use of the Service after changes constitutes acceptance.
          </p>
        </Section>

        <Section title="10. Contact">
          <p className="text-gray-700 dark:text-gray-300">
            Questions about these Terms:{' '}
            <Link href="/contact" className="underline text-blue-600 dark:text-blue-400">
              contact us
            </Link>
            .
          </p>
        </Section>
      </main>
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-bold text-gray-900 dark:text-gray-100 mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  )
}
