import type { Metadata } from 'next'
import { Header } from '@/components/ui/Header'
import { AdSlot } from '@/components/ads/AdSlot'
import { TreksGrid } from '@/components/trek/TreksGrid'
import { db } from '@/lib/db'
import type { TrekVerdictData } from '@/types'

const BASE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://thepeakweather.com'

export const metadata: Metadata = {
  title: 'Browse Treks & Trails Worldwide',
  description: 'Explore 90+ famous treks from Everest Base Camp to the Inca Trail, with AI-powered GO/CAUTION/NO-GO safety verdicts.',
  alternates: { canonical: '/treks' },
}

function buildTreksJsonLd(treks: { slug: string; name: string; country: string; summitElevation: number }[]) {
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: BASE },
          { '@type': 'ListItem', position: 2, name: 'Treks & Trails', item: `${BASE}/treks` },
        ],
      },
      {
        '@type': 'CollectionPage',
        '@id': `${BASE}/treks`,
        url: `${BASE}/treks`,
        name: 'Treks & Trails Worldwide',
        description: 'Browse 90+ famous treks with AI-powered GO/CAUTION/NO-GO safety verdicts.',
        isPartOf: { '@id': `${BASE}/#website` },
        mainEntity: {
          '@type': 'ItemList',
          itemListElement: treks.map((t, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            url: `${BASE}/trek/${t.slug}`,
            name: t.name,
          })),
        },
      },
    ],
  }
}

export const revalidate = 900

async function getTreksWithVerdicts() {
  let treks: Awaited<ReturnType<typeof db.trek.findMany<{ include: { verdict: true } }>>> = []
  try {
    treks = await db.trek.findMany({
      orderBy: [{ popular: 'desc' }, { name: 'asc' }],
      include: { verdict: true },
    })
  } catch {
    return []
  }

  return treks.map((t) => {
    let verdictData: TrekVerdictData | null = null
    if (t.verdict) {
      try {
        verdictData = JSON.parse(t.verdict.verdict) as TrekVerdictData
        if (t.verdict.expiresAt < new Date()) verdictData = null
      } catch {}
    }
    return {
      id: t.id,
      slug: t.slug,
      name: t.name,
      country: t.country,
      region: t.region,
      summitElevation: t.summitElevation,
      difficulty: t.difficulty,
      popular: t.popular,
      verdictData,
    }
  })
}

export default async function TreksPage() {
  const treks = await getTreksWithVerdicts()
  const withVerdict = treks.filter((t) => t.verdictData).length
  const jsonLd = buildTreksJsonLd(treks)

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Header />
      <main className="max-w-5xl mx-auto px-4 pb-12 pt-8">

        {/* ── Hero ─────────────────────────────────────────────────────── */}
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold text-gray-900 dark:text-gray-100 mb-2">
            Treks & Trails Worldwide
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            {treks.length} treks ·{' '}
            {withVerdict > 0
              ? `${withVerdict} with live AI verdicts`
              : 'AI verdicts generated on first visit'
            }
          </p>
        </div>

        {/* ── Ad ────────────────────────────────────────────────────────── */}
        <AdSlot format="leaderboard" className="min-h-[90px] mb-8" />

        {/* ── Filter grid (client component) ──────────────────────────── */}
        <TreksGrid treks={treks} />

        {/* ── Info strip ──────────────────────────────────────────────── */}
        <div className="mt-12 rounded-2xl bg-blue-50 dark:bg-blue-950 border border-blue-100 dark:border-blue-800 p-5 text-sm text-blue-800 dark:text-blue-200">
          <p className="font-semibold mb-1">How AI verdicts work</p>
          <p>
            Each verdict is generated by Claude analysing current and forecast weather at both the trailhead and summit,
            considering altitude, difficulty, and risk factors. Verdicts are cached for 4 hours and refreshed automatically on each visit.
          </p>
        </div>
      </main>
    </>
  )
}
